# Gitpod Configuration for React Native Expo
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8081
    onOpen: notify
    name: Metro Bundler
  - port: 19000
    onOpen: notify
    name: Expo Dev Server
  - port: 19001
    onOpen: ignore
  - port: 19002
    onOpen: ignore

tasks:
  - name: Install Dependencies
    init: |
      npm install
      npx expo install
    command: |
      echo "Ready to start development!"
      echo "Run 'npm start' to start the Expo development server"

vscode:
  extensions:
    - ms-vscode.vscode-typescript-next
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
